# МЕТОДЫ СОРТИРОВКИ

In [3]:
import numpy as np

## 1. СОРТИРОВКА ПУЗЫРЬКОМ

Для понимания и реализации этот алгоритм — простейший, но эффективен он лишь для небольших массивов. Cложность алгоритма: $$O(n^2)$$

Алгоритм считается учебным и практически не применяется вне учебной литературы, вместо него на практике применяются более эффективные алгоритмы сортировки. 

In [2]:
a = np.random.poisson(10, 10)
a

array([11, 16, 10, 12,  5,  8,  9,  9, 11, 14])

In [3]:
for j in range(len(a)-1):
    for i in range(len(a)-1):
        if a[i] > a[i+1]:
            temp = a[i]
            a[i] = a[i+1]
            a[i+1] = temp

In [4]:
a

array([ 5,  8,  9,  9, 10, 11, 11, 12, 14, 16])

In [5]:
#ИЛИ ТАК

a = np.random.poisson(10, 10)
for j in range(len(a)-1):
    for i in range(len(a)-1):
        if a[i] > a[i+1]:
            a[i], a[i+1] = a[i+1], a[i]
a

array([ 6,  7,  8,  9,  9, 10, 10, 11, 11, 15])

In [33]:
#ИЛИ ФУНКЦИЯ

def bubble(lst):
    for j in range(len(lst)-1):
        for i in range(len(lst)-1):
            if lst[i] > lst[i+1]:
                lst[i], lst[i+1] = lst[i+1], lst[i]
    return lst

In [34]:
bubble(a)

array([ 6,  7,  8,  9,  9, 10, 10, 11, 11, 15])

## 2. СОРТИРОВКА ВЫБОРОМ

Сортировка выбором (Selection sort) — алгоритм сортировки. Может быть как устойчивый, так и неустойчивый. Простой алгоритм сортировки со сложностью $$O(n^2)$$, где n — количество элементов для сортировки.

Этот алгоритм имеет плюс в сравнении, например, с сортировкой методом пузырька в том, что замена элементов производится для каждого элемента один раз, что ускоряет работу всего алгоритма.

In [8]:
b = np.random.poisson(10, 10)
b

array([12,  6, 15,  8, 10,  8, 12, 10,  8, 12])

In [9]:
for i in range(len(b)-1):
    min = i
    
    for j in range(i+1, len(b)):
        if b[min] > b[j]:
            min == j
            
    if min != i:
        temp = b[j]
        b[j] = b[min]
        b[min] = temp
        
#????

In [10]:
b

array([12,  6, 15,  8, 10,  8, 12, 10,  8, 12])

In [11]:
#ИЛИ ТАК

b = np.random.poisson(10, 10)

for i in range(len(b)-1):
        for j in range(i+1, len(b)):
            if b[j] < b[i]:
                b[j], b[i] = b[i], b[j]
                
b

array([ 5,  9,  9,  9, 10, 10, 11, 11, 13, 16])

In [35]:
#ИЛИ ФУНКЦИЯ

def choice(lst):

    for i in range(len(lst)-1):
            for j in range(i+1, len(lst)):
                if lst[j] < lst[i]:
                    lst[j], lst[i] = lst[i], lst[j]

    return lst

In [36]:
choice(b)

array([ 5,  9,  9,  9, 10, 10, 11, 11, 13, 16])

## 3. БЫСТРАЯ СОРТИРОВКА

Этот один из самых быстрых алгоритмов сортировки, получил свое название от стандартной библиотеки языка Си – quicksort. 

Алгоритм разработан на базе алгоритма пузырьковой сортировки. Улучшение старого алгоритмов заключается в том, что перестановки производятся для элементов на наиболее возможном расстоянии и сам список последовательно разделяется на отдельные группы.

Ожидаемое время выполнения алгоритма сортировки составляет $$O(n * log n)$$

In [59]:
c = np.random.poisson(10, 10)
c

array([10, 10, 11,  7,  7,  8, 10,  7, 13,  9])

In [60]:
def quicksort(c):
    if len(set(c)) <= 1:
        return c
    else:
        less = []
        more = []
        ecval = []
        mid = (c[0] + c[len(c)-1]) / 2
        for num in c:
            if num < mid:
                less.append(num)
            elif num == mid:
                ecval.append(num)
            else: more.append(num)
        return quicksort(less) + quicksort(ecval) + quicksort(more)

In [61]:
quicksort(c=c)

[7, 7, 7, 8, 9, 10, 10, 10, 11, 13]

## СРАВНЕНИЕ ВРЕМЕНИ

In [17]:
import time

**сортировка пузырьком**

In [18]:
check_time = np.random.poisson(10,10000)

In [19]:
start_time = time.time()
bubble(check_time)
print("СОРТИРОВКА ПУЗЫРЬКОМ: --- %s seconds ---" % (time.time() - start_time))

СОРТИРОВКА ПУЗЫРЬКОМ: --- 43.51575469970703 seconds ---


In [22]:
check_time

array([ 0,  1,  1, ..., 24, 24, 29])

**сортировка выбором**

In [37]:
check_time = np.random.poisson(10,10000)

In [38]:
start_time = time.time()
choice(check_time)
print("СОРТИРОВКА ВЫБОРОМ: --- %s seconds ---" % (time.time() - start_time))

СОРТИРОВКА ВЫБОРОМ: --- 15.28161907196045 seconds ---


In [39]:
check_time

array([ 1,  1,  1, ..., 24, 24, 24])

**сортировка быстрая**

In [72]:
check_time = np.random.poisson(10,10000)

In [73]:
start_time = time.time()
check_time_quick = np.array(quicksort(c=check_time))
print("СОРТИРОВКА БЫСТРАЯ--- %s seconds ---" % (time.time() - start_time))

СОРТИРОВКА БЫСТРАЯ--- 0.12502694129943848 seconds ---


In [74]:
check_time_quick

array([ 0,  1,  1, ..., 23, 24, 24])

In [19]:
a = [12, 12, 33, 12, 12]
a

[12, 12, 33, 12, 12]

In [22]:
def function(lst):
    i = 0
    j = 0
    f = []
    s = []
    for i in range(len(a)-1):
        for j in range(i+1, len(a)):
            if a[i] == a[j]:
                s = s + a[i]
                if s == f:
                    break
                f = list.copy(s)
                s = function(s)
    return s

In [23]:
print(function(a))

RecursionError: maximum recursion depth exceeded in comparison